config/routes.rb
Rails.application.routes.draw do
  resources :demand_list do
    collection do
      get 'import_csv_new'
      post 'import_csv'
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  get 'home/index'
  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role?('admin')
      can :read, :all
      can :access, :rails_admin
      can :dashboard
      if user.has_role?('superadmin')
        can :manage, :all
      else
        can :manage, [] # A
      end
    else
      can :read, [] # B
      can :create, [] # C
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/demand_list.rb
# csv操作を可能にするライブラリ
require 'csv'
# 文字コード操作をおこなうライブラリ(nkfの方がいいかも)
require 'kconv'

class DemandList < ActiveRecord::Base
  # CSVファイルを読み込み、ユーザーを登録する
  def self.import_csv(csv_file)
    # csvファイルを受け取って文字列にする
    csv_text = csv_file.read

    data = []

    #文字列をUTF-8に変換
    CSV.parse(Kconv.toutf8(csv_text)) do |row|

      demand_list = DemandList.new
      demand_list.customer_name = row[0]  #csvの2列目を格納
      demand_list.address_1 = row[1]
      demand_list.address_2 = row[2]
      demand_list.estate_type = row[3]
      demand_list.price = row[4]
      demand_list.wayside = row[5]
      demand_list.station  = row[6]
      demand_list.walking_time = row[7]
      demand_list.land_area = row[8]
      demand_list.building_area = row[9]
      demand_list.exclusive_area = row[10]

      demand_list.save
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :roles

  def has_role?(name)
    self.roles.where(name: name).length > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # デフォルトでログイン済みのユーザーのみ閲覧できるよう設定
  before_action :authenticate_user!

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/demand_list_controller.rb
class DemandListController < ApplicationController
  def index
    @DemandLists = DemandList.all
  end

  def import_csv_new
  end

  def import_csv
    respond_to do |format|
      if DemandList.import_csv(params[:csv_file])
        format.html { redirect_to home_index_path }
        format.json { head :no_content }
      else
        format.html { redirect_to home_index_path, :notice => "CSVファイルの読み込みに失敗しました。" }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
# 戻り値が true ならサインイン済み。
# => user_signed_in?
# サインインしている全ユーザー取得
# => current_user
# ユーザーのセッション情報
# => user_session

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demand_list_helper.rb
module DemandListHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/demand_list/import_csv_new.html.erb
<h1>顧客要望一覧（CSVファイル）</h1>

<%= form_tag({controller: "demand_list", action: "import_csv", method: "post"}, {multipart: true}) do %>
  <div class="field">
    <%= label_tag "CSVファイルを選択" %><br>
    <%= file_field_tag :csv_file %>
  </div>

  <div class="actions">
    <%= submit_tag "CSVファイルを読み込む"%>
  </div>
<% end %>

<%= link_to 'ホームに戻る', home_index_path %>

app/views/demand_list/index.html.erb
<h1>顧客要望一覧TOP</h1>

<table class="table table-striped table-bordered table-hover">
  <tr>
    <th>要望管理番号</th>
    <th>顧客名</th>
    <th>所在地名1</th>
    <th>所在地名2</th>
    <th>物件タイプ</th>
    <th>価格</th>
    <th>沿線略称</th>
    <th>駅名</th>
    <th>徒歩（分）</th>
    <th>土地面積</th>
    <th>建物面積</th>
    <th>専有面積</th>
    <th>登録日時</th>
    <th>更新日時</th>
  </tr>
  <% @DemandLists.each do |item| %>
  <tr>
    <td><%= item.id  %></td>
    <td><%= item.customer_name  %></td>
    <td><%= item.address_1  %></td>
    <td><%= item.address_2  %></td>
    <td><%= item.estate_type  %></td>
    <td><%= item.price  %></td>
    <td><%= item.wayside  %></td>
    <td><%= item.station  %></td>
    <td><%= item.walking_time  %></td>
    <td><%= item.land_area  %></td>
    <td><%= item.building_area  %></td>
    <td><%= item.exclusive_area  %></td>
    <td><%= item.created_at  %></td>
    <td><%= item.updated_at  %></td>
  </tr>
  <% end %>
</table>

<%= link_to 'ホームに戻る', home_index_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>

<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to "Settings", edit_user_registration_path, :class => "navbar-link" %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "navbar-link" %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
<% end %>

<% if user_signed_in? %>
<%= link_to '顧客要望一覧のCSVをアップロード', import_csv_new_demand_list_index_path, :class => 'btn' %>
<% end %>

<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RealEstateManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>